### ISSUE TITLE
Troubleshooting should mention "Enable DualSense" option

### ISSUE THREAD

**Issue by Terrobility** [CircumSpector/DS4WDocs#7]
It seems the PS5 controller support requires a button toggle. However, this was NOT mentioned anywhere so I wasted 10 mins digging through troubleshooting. It was only by chance that I found the "Device Options" button in Settings with the option to enable "DualSense Controller Support". Any chance that can be the first troubleshooting step mentioned on the guide?

**Comment by nefarius** [comment]
You can add that yourself anytime. That's how FOSS works. We're happy to accept Pull Requests any time for these sorts of things. The entire site is comunity-run so obviously it can happen that information is outdated or incomplete.

**Comment by Terrobility** [comment]
Forked and created pull request #8 to fix the issue
